theme: jekyll-theme-tactile
title: Teknoir Wiki
url: https://teknoir.github.io
# email: anders.aslund@teknoir.ai
description: >- # this means to ignore newlines until "baseurl:"
  Documentation project for the Teknoir platform and partners.
github_username:  teknoir
twitter_username: teknoir

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-relative-links

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/